Repository CA-G12/API-Project-Agha-AliShanti, pull requests merged in 2022-08, with the labels that each got.

#5 create the file project structure
  index.html
  js/dom.js
  js/main.js
  style/style.css
Labels: Done

#6 make the repos cards and style it
  index.html
  style/style.css
Labels: Done

#7 make the search bar and style it
  index.html
  style/style.css
Labels: reviewed

#12 create the user section and styling it
  index.html
  style/style.css
Labels: Done

#13 create the fetch function
  js/main.js
Labels: reviewed

#14 crate the function repos card
  js/main.js
Labels: Done

#15 make the generate user dom function
  js/main.js
Labels: Done

#21 create the function wich handle the case that the user have acount in…
  js/main.js
Labels: reviewed

#22 create the quotes function
  index.html
  js/dom.js
  js/main.js
  style/style.css
Labels: Done

#23 make function that return a random index
  js/main.js
Labels: reviewed

#27 make function to handle Network Errors
  index.html
  js/main.js
  style/style.css
Labels: reviewed, Done

#28 create the function to sum stars
  js/main.js
Labels: Done

#29 create sort function
  js/main.js
Labels: Done

#32 styling the repo card with max stars
  js/main.js
  style/style.css
Labels: reviewed

#33 add some animation
  style/style.css
Labels: Done

#35 make the media query for the search bar
  style/style.css
Labels: reviewed
